// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aomvlmafqutkfbmocyjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvbXZsbWFmcXV0a2ZibW9jeWp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTIyMjksImV4cCI6MjA2MzkyODIyOX0.9y2sbRDphrXgzve_XbPwae80cjaRqxI6gjw9ITuQCOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);